kind: pipeline
type: kubernetes
name: minsky-landing

steps:
  # - name: test-node-14
  #   image: node:14
  #   commands:
  #     - yarn
  #     - yarn build

  - name: docker-registry
    image: plugins/docker
    settings:
      repo: docker.minsky.cc/minsky/landing
      registry: docker.minsky.cc
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master

  - name: deploy
    image: pelotech/drone-helm3
    settings:
      mode: upgrade
      chart: ./chart
      release: landing
      namespace: minsky
    environment:
      KUBE_API_SERVER:
        from_secret: kubernetes_api_server
      KUBE_TOKEN:
        from_secret: kubernetes_token
    when:
      branch:
        - master
    depends_on:
      - docker-registry

  - name: telegram-notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to_id
    when:
      status:
        - failure
        - success
